// Login constant
export const USER_EMAIL_ADDRESS = "USER_EMAIL_ADDRESS";
export const USER_PASSWORD = "USER_PASSWORD";
export const PUBLIC_AUTH_LOGIN_REQUEST = "PUBLIC_AUTH_LOGIN_REQUEST";
export const PUBLIC_AUTH_LOGIN_SUCCESS = "PUBLIC_AUTH_LOGIN_SUCCESS";
export const PUBLIC_AUTH_LOGIN_FAILURE = "PUBLIC_AUTH_LOGIN_FAILURE";
