// Login constant
export const USER_EMAIL_ADDRESS = "USER_EMAIL_ADDRESS";
export const IS_USER_EMAIL_ADDRESS_ERROR = "IS_USER_EMAIL_ADDRESS_ERROR";
export const USER_PASSWORD = "USER_PASSWORD";
export const IS_USER_PASSWORD_ERROR = "IS_USER_PASSWORD_ERROR";
export const PUBLIC_AUTH_LOGIN_REQUEST = "PUBLIC_AUTH_LOGIN_REQUEST";
export const PUBLIC_AUTH_LOGIN_SUCCESS = "PUBLIC_AUTH_LOGIN_SUCCESS";

// Verify 2FA
export const PUBLIC_USER_OTP_2FA = "PUBLIC_USER_OTP_2FA";
export const IS_PUBLIC_USER_OTP_2FA_ERROR = "IS_PUBLIC_USER_OTP_2FA_ERROR";

export const PUBLIC_VERIFY_2FA_REQUEST = "PUBLIC_VERIFY_2FA_REQUEST";
export const PUBLIC_VERIFY_2FA_SUCCESS = "PUBLIC_VERIFY_2FA_SUCCESS";

// Check two factor authentication
export const IS_2FA_AUTHENTICATION = "IS_2FA_AUTHENTICATION";

// Remember password
