export const contactUserList = [
  {
    id: "1",
    firstName: "John",
    lastName: "Doe",
    emailAddress: "john.doe@example.com",
    phoneNumber: "123-456-7890",
    role: "Teacher",
  },
  {
    id: "2",
    firstName: "Jane",
    lastName: "Smith",
    emailAddress: "jane.smith@example.com",
    phoneNumber: "234-567-8901",
    role: "Student",
  },
  {
    id: "3",
    firstName: "Michael",
    lastName: "Brown",
    emailAddress: "michael.brown@example.com",
    phoneNumber: "345-678-9012",
    role: "NonTeacher",
  },
  {
    id: "4",
    firstName: "Emily",
    lastName: "Johnson",
    emailAddress: "emily.johnson@example.com",
    phoneNumber: "456-789-0123",
    role: "Teacher",
  },
  {
    id: "5",
    firstName: "Chris",
    lastName: "Lee",
    emailAddress: "chris.lee@example.com",
    phoneNumber: "567-890-1234",
    role: "Student",
  },
  {
    id: "6",
    firstName: "Sarah",
    lastName: "Williams",
    emailAddress: "sarah.williams@example.com",
    phoneNumber: "678-901-2345",
    role: "NonTeacher",
  },
  {
    id: "7",
    firstName: "David",
    lastName: "Jones",
    emailAddress: "david.jones@example.com",
    phoneNumber: "789-012-3456",
    role: "Teacher",
  },
  {
    id: "8",
    firstName: "Anna",
    lastName: "Garcia",
    emailAddress: "anna.garcia@example.com",
    phoneNumber: "890-123-4567",
    role: "Student",
  },
  {
    id: "9",
    firstName: "James",
    lastName: "Martinez",
    emailAddress: "james.martinez@example.com",
    phoneNumber: "901-234-5678",
    role: "NonTeacher",
  },
  {
    id: "10",
    firstName: "Laura",
    lastName: "Rodriguez",
    emailAddress: "laura.rodriguez@example.com",
    phoneNumber: "012-345-6789",
    role: "Teacher",
  },
  {
    id: "11",
    firstName: "Daniel",
    lastName: "Martinez",
    emailAddress: "daniel.martinez@example.com",
    phoneNumber: "123-456-7890",
    role: "Student",
  },
  {
    id: "12",
    firstName: "Sophia",
    lastName: "Hernandez",
    emailAddress: "sophia.hernandez@example.com",
    phoneNumber: "234-567-8901",
    role: "NonTeacher",
  },
  {
    id: "13",
    firstName: "Matthew",
    lastName: "Lopez",
    emailAddress: "matthew.lopez@example.com",
    phoneNumber: "345-678-9012",
    role: "Teacher",
  },
  {
    id: "14",
    firstName: "Olivia",
    lastName: "Gonzalez",
    emailAddress: "olivia.gonzalez@example.com",
    phoneNumber: "456-789-0123",
    role: "Student",
  },
  {
    id: "15",
    firstName: "Jacob",
    lastName: "Wilson",
    emailAddress: "jacob.wilson@example.com",
    phoneNumber: "567-890-1234",
    role: "NonTeacher",
  },
  {
    id: "16",
    firstName: "Amelia",
    lastName: "Anderson",
    emailAddress: "amelia.anderson@example.com",
    phoneNumber: "678-901-2345",
    role: "Teacher",
  },
  {
    id: "17",
    firstName: "Joshua",
    lastName: "Thomas",
    emailAddress: "joshua.thomas@example.com",
    phoneNumber: "789-012-3456",
    role: "Student",
  },
  {
    id: "18",
    firstName: "Mia",
    lastName: "Taylor",
    emailAddress: "mia.taylor@example.com",
    phoneNumber: "890-123-4567",
    role: "NonTeacher",
  },
  {
    id: "19",
    firstName: "Andrew",
    lastName: "Moore",
    emailAddress: "andrew.moore@example.com",
    phoneNumber: "901-234-5678",
    role: "Teacher",
  },
  {
    id: "20",
    firstName: "Isabella",
    lastName: "Jackson",
    emailAddress: "isabella.jackson@example.com",
    phoneNumber: "012-345-6789",
    role: "Student",
  },
  {
    id: "21",
    firstName: "Ryan",
    lastName: "Martin",
    emailAddress: "ryan.martin@example.com",
    phoneNumber: "123-456-7890",
    role: "NonTeacher",
  },
  {
    id: "22",
    firstName: "Ava",
    lastName: "Lee",
    emailAddress: "ava.lee@example.com",
    phoneNumber: "234-567-8901",
    role: "Teacher",
  },
  {
    id: "23",
    firstName: "Brandon",
    lastName: "Perez",
    emailAddress: "brandon.perez@example.com",
    phoneNumber: "345-678-9012",
    role: "Student",
  },
  {
    id: "24",
    firstName: "Chloe",
    lastName: "Thompson",
    emailAddress: "chloe.thompson@example.com",
    phoneNumber: "456-789-0123",
    role: "NonTeacher",
  },
  {
    id: "25",
    firstName: "Tyler",
    lastName: "White",
    emailAddress: "tyler.white@example.com",
    phoneNumber: "567-890-1234",
    role: "Teacher",
  },
  {
    id: "26",
    firstName: "Ella",
    lastName: "Harris",
    emailAddress: "ella.harris@example.com",
    phoneNumber: "678-901-2345",
    role: "Student",
  },
  {
    id: "27",
    firstName: "Dylan",
    lastName: "Sanchez",
    emailAddress: "dylan.sanchez@example.com",
    phoneNumber: "789-012-3456",
    role: "Admin",
  },
  {
    id: "28",
    firstName: "Grace",
    lastName: "Clark",
    emailAddress: "grace.clark@example.com",
    phoneNumber: "890-123-4567",
    role: "Teacher",
  },
  {
    id: "29",
    firstName: "Jason",
    lastName: "Ramirez",
    emailAddress: "jason.ramirez@example.com",
    phoneNumber: "901-234-5678",
    role: "Student",
  },
  {
    id: "30",
    firstName: "Lily",
    lastName: "Lewis",
    emailAddress: "lily.lewis@example.com",
    phoneNumber: "012-345-6789",
    role: "Admin",
  },
  {
    id: "31",
    firstName: "Kevin",
    lastName: "Robinson",
    emailAddress: "kevin.robinson@example.com",
    phoneNumber: "123-456-7890",
    role: "Teacher",
  },
  {
    id: "32",
    firstName: "Zoey",
    lastName: "Walker",
    emailAddress: "zoey.walker@example.com",
    phoneNumber: "234-567-8901",
    role: "Student",
  },
  {
    id: "33",
    firstName: "Justin",
    lastName: "Young",
    emailAddress: "justin.young@example.com",
    phoneNumber: "345-678-9012",
    role: "Admin",
  },
  {
    id: "34",
    firstName: "Layla",
    lastName: "Allen",
    emailAddress: "layla.allen@example.com",
    phoneNumber: "456-789-0123",
    role: "Teacher",
  },
  {
    id: "35",
    firstName: "Nathan",
    lastName: "King",
    emailAddress: "nathan.king@example.com",
    phoneNumber: "567-890-1234",
    role: "Student",
  },
  {
    id: "36",
    firstName: "Aubrey",
    lastName: "Wright",
    emailAddress: "aubrey.wright@example.com",
    phoneNumber: "678-901-2345",
    role: "Admin",
  },
  {
    id: "37",
    firstName: "Lucas",
    lastName: "Scott",
    emailAddress: "lucas.scott@example.com",
    phoneNumber: "789-012-3456",
    role: "Teacher",
  },
  {
    id: "38",
    firstName: "Hannah",
    lastName: "Torres",
    emailAddress: "hannah.torres@example.com",
    phoneNumber: "890-123-4567",
    role: "Student",
  },
  {
    id: "39",
    firstName: "Zachary",
    lastName: "Nguyen",
    emailAddress: "zachary.nguyen@example.com",
    phoneNumber: "901-234-5678",
    role: "Admin",
  },
  {
    id: "40",
    firstName: "Samantha",
    lastName: "Hill",
    emailAddress: "samantha.hill@example.com",
    phoneNumber: "012-345-6789",
    role: "Teacher",
  },
  {
    id: "41",
    firstName: "Ethan",
    lastName: "Flores",
    emailAddress: "ethan.flores@example.com",
    phoneNumber: "123-456-7890",
    role: "Student",
  },
  {
    id: "42",
    firstName: "Natalie",
    lastName: "Green",
    emailAddress: "natalie.green@example.com",
    phoneNumber: "234-567-8901",
    role: "Admin",
  },
  {
    id: "43",
    firstName: "Landon",
    lastName: "Adams",
    emailAddress: "landon.adams@example.com",
    phoneNumber: "345-678-9012",
    role: "Teacher",
  },
  {
    id: "44",
    firstName: "Victoria",
    lastName: "Nelson",
    emailAddress: "victoria.nelson@example.com",
    phoneNumber: "456-789-0123",
    role: "Student",
  },
  {
    id: "45",
    firstName: "Caleb",
    lastName: "Carter",
    emailAddress: "caleb.carter@example.com",
    phoneNumber: "567-890-1234",
    role: "Admin",
  },
  {
    id: "46",
    firstName: "Lillian",
    lastName: "Mitchell",
    emailAddress: "lillian.mitchell@example.com",
    phoneNumber: "678-901-2345",
    role: "Teacher",
  },
  {
    id: "47",
    firstName: "Henry",
    lastName: "Perez",
    emailAddress: "henry.perez@example.com",
    phoneNumber: "789-012-3456",
    role: "Student",
  },
  {
    id: "48",
    firstName: "Sofia",
    lastName: "Roberts",
    emailAddress: "sofia.roberts@example.com",
    phoneNumber: "890-123-4567",
    role: "Admin",
  },
  {
    id: "49",
    firstName: "Isaac",
    lastName: "Turner",
    emailAddress: "isaac.turner@example.com",
    phoneNumber: "901-234-5678",
    role: "Teacher",
  },
  {
    id: "50",
    firstName: "Brooklyn",
    lastName: "Phillips",
    emailAddress: "brooklyn.phillips@example.com",
    phoneNumber: "012-345-6789",
    role: "Student",
  },
];
