export const APPLICATION_MENU = "APPLICATION_MENU";

// My approval
export const MY_APPROVAL_OPTION = "MY_APPROVAL_OPTION";
export const APPROVAL_SEARCH_INPUT = "APPROVAL_SEARCH_INPUT";

export const MY_APPROVAL_REQUEST = "MY_APPROVAL_REQUEST";
export const MY_APPROVAL_SUCCESS = "MY_APPROVAL_SUCCESS";
export const MY_APPROVAL_FAILURE = "MY_APPROVAL_FAILURE";

// Appyl leave form
export const LEAVE_TYPE = "LEAVE_TYPE";
export const IS_LEAVE_TYPE_ERROR = "IS_LEAVE_TYPE_ERROR";
export const REQUESTED_DATE = "REQUESTED_DATE";
export const FROM_DATE = "FROM_DATE";
export const IS_FROM_DATE_ERROR = "IS_FROM_DATE_ERROR";
export const TO_DATE = "TO_DATE";
export const IS_TO_DATE_ERROR = "IS_TO_DATE_ERROR";
export const NUMBER_OF_DAYS = "NUMBER_OF_DAYS";
export const LEAVE_REASON = "LEAVE_REASON";
export const IS_LEAVE_REASON_ERROR = "IS_LEAVE_REASON_ERROR";
export const AFTER_APPLY_LEAVE = "AFTER_APPLY_LEAVE";

export const APPLY_LEAVE_REQUEST = "APPLY_LEAVE_REQUEST";
export const APPLY_LEAVE_SUCCESS = "APPLY_LEAVE_SUCCESS";
export const APPLY_LEAVE_FAILURE = "APPLY_LEAVE_FAILURE";
