// Device details
export const BROWSER_NAME = "BROWSER_NAME";
export const BROWSER_VERSION = "BROWSER_VERSION";
export const BROWSER_ID = "BROWSER_ID";
export const BROWSER_OS = "BROWSER_OS";
export const BROWSER_ENGINE = "BROWSER_ENGINE";
export const IP_ADDRESS = "IP_ADDRESS";
export const MAC_ADDRESS = "MAC_ADDRESS";
export const LOCATION_LOGINTUDE = "LOCATION_LOGINTUDE";
export const LOCATION_LATITUDE = "LOCATION_LATITUDE";

// Update device details
export const UPDATE_DEVICE_DETAILS_REQUEST = "UPDATE_DEVICE_DETAILS_REQUEST";
export const UPDATE_DEVICE_DETAILS_SUCCESS = "UPDATE_DEVICE_DETAILS_SUCCESS";
export const UPDATE_DEVICE_DETAILS_FAILURE = "UPDATE_DEVICE_DETAILS_FAILURE";

// Get device details
export const DEVICE_DETAILS_REQUEST = "DEVICE_DETAILS_REQUEST";
export const DEVICE_DETAILS_SUCCESS = "DEVICE_DETAILS_SUCCESS";
export const DEVICE_DETAILS_FAILURE = "DEVICE_DETAILS_FAILURE";
