export const APPLICATION_MENU = "APPLICATION_MENU";

// My approval
export const MY_APPROVAL_OPTION = "MY_APPROVAL_OPTION";
export const APPROVAL_SEARCH_INPUT = "APPROVAL_SEARCH_INPUT";
// My approval list
export const MY_APPROVAL_REQUEST = "MY_APPROVAL_REQUEST";
export const MY_APPROVAL_SUCCESS = "MY_APPROVAL_SUCCESS";
export const MY_APPROVAL_FAILURE = "MY_APPROVAL_FAILURE";
// Appyl leave form
export const LEAVE_TYPE = "LEAVE_TYPE";
export const IS_LEAVE_TYPE_ERROR = "IS_LEAVE_TYPE_ERROR";
export const REQUESTED_DATE = "REQUESTED_DATE";
export const FROM_DATE = "FROM_DATE";
export const IS_FROM_DATE_ERROR = "IS_FROM_DATE_ERROR";
export const TO_DATE = "TO_DATE";
export const IS_TO_DATE_ERROR = "IS_TO_DATE_ERROR";
export const NUMBER_OF_DAYS = "NUMBER_OF_DAYS";
export const LEAVE_REASON = "LEAVE_REASON";
export const IS_LEAVE_REASON_ERROR = "IS_LEAVE_REASON_ERROR";
// Apply new leave and work from home request
export const APPLY_LEAVE_REQUEST = "APPLY_LEAVE_REQUEST";
export const APPLY_LEAVE_SUCCESS = "APPLY_LEAVE_SUCCESS";
export const APPLY_LEAVE_FAILURE = "APPLY_LEAVE_FAILURE";

// Application
// New Application
export const APPLICATION_SUBJECT = "APPLICATION_SUBJECT";
export const IS_APPLICATION_SUBJECT_ERROR = "IS_APPLICATION_SUBJECT_ERROR";
export const APPLICATION_SUBMITED_TO = "APPLICATION_SUBMITED_TO";
export const IS_APPLICATION_SUBMITED_TO_ERROR = "IS_APPLICATION_SUBMITED_TO_ERROR";
export const APPLICATION_BODY = "APPLICATION_BODY";
// Apply new application request
export const NEW_APPLICATION_REQUEST = "NEW_APPLICATION_REQUEST";
export const NEW_APPLICATION_SUCCESS = "NEW_APPLICATION_SUCCESS";
export const NEW_APPLICATION_FAILURE = "NEW_APPLICATION_FAILURE";
// Application list
export const MY_APPLICATION_REQUEST = "MY_APPLICATION_REQUEST";
export const MY_APPLICATION_SUCCESS = "MY_APPLICATION_SUCCESS";
export const MY_APPLICATION_FAILURE = "My_APPLICATION_FAILURE";
// Application Details
export const MY_APPLICATION_DETAILS_REQUEST = "MY_APPLICATION_DETAILS_REQUEST";
export const MY_APPLICATION_DETAILS_SUCCESS = "MY_APPLICATION_DETAILS_SUCCESS";
export const MY_APPLICATION_DETAILS_FAILURE = "MY_APPLICATION_DETAILS_FAILURE";
