// Dashboard setting

// Edit profile

// Notification setting

// Setup 2FA
// Get details of 2FA
export const GET_DETAILS_2FA_REQUEST = "GET_DETAILS_2FA_REQUEST";
export const GET_DETAILS_2FA_SUCCESS = "GET_DETAILS_2FA_SUCCESS";
// Passkey
export const UPDATE_PASSKEY_REQUEST = "UPDATE_PASSKEY_REQUEST";
export const UPDATE_PASSKEY_SUCCESS = "UPDATE_PASSKEY_SUCCESS";
// UserIs2FA
export const USER_IS_2FA = "USER_IS_2FA";

export const UPDATE_USER_IS_2FA_REQUEST = "UPDATE_USER_IS_2FA_REQUEST";
export const UPDATE_USER_IS_2FA_SUCCESS = "UPDATE_USER_IS_2FA_SUCCESS";
// Verify 2FA => Generate QR Code
export const GENERATE_QR_CODE_REQUEST = "GENERATE_QR_CODE_REQUEST";
export const GENERATE_QR_CODE_SUCCESS = "GENERATE_QR_CODE_SUCCESS";
// Verify 2FA => OTP INPUT
export const USER_OTP_2FA = "USER_OTP_2FA";

export const VERIFY_2FA_OTP_REQUEST = "VERIFY_2FA_OTP_REQUEST";
export const VERIFY_2FA_OTP_SUCCESS = "VERIFY_2FA_OTP_SUCCESS";
// Preffered 2FA method
export const PREFFERED_2FA_METHOD_OPTION = "PREFFERED_2FA_METHOD_OPTION";

export const UPDATE_PREFFERED_2FA_METHOD_REQUEST =
  "UPDATE_PREFFERED_2FA_METHOD_REQUEST";
export const UPDATE_PREFFERED_2FA_METHOD_SUCCESS =
  "UPDATE_PREFFERED_2FA_METHOD_SUCCESS";
// Method 2FA => User Authenticator app
export const UPDATE_2FA_USER_AUTHENTICATOR_APP_REQUEST =
  "UPDATE_2FA_USER_AUTHENTICATOR_APP_REQUEST";
export const UPDATE_2FA_USER_AUTHENTICATOR_APP_SUCCESS =
  "UPDATE_2FA_USER_AUTHENTICATOR_APP_SUCCESS";
// Method 2FA => SMS/Text
export const UPDATE_2FA_USER_SMS_TEXT_REQUEST =
  "UPDATE_2FA_USER_SMS_TEXT_REQUEST";
export const UPDATE_2FA_USER_SMS_TEXT_SUCCESS =
  "UPDATE_2FA_USER_SMS_TEXT_SUCCESS";
// Method 2FA => Security keys
export const UPDATE_2FA_USER_SECURITY_KEY_REQUEST =
  "UPDATE_2FA_USER_SECURITY_KEY_REQUEST";
export const UPDATE_2FA_USER_SECURITY_KEY_SUCCESS =
  "UPDATE_2FA_USER_SECURITY_KEY_SUCCESS";
// Method 2FA => Recovery code
export const UPDATE_2FA_USER_RECOVERY_CODE_REQUEST =
  "UPDATE_2FA_USER_RECOVERY_CODE_REQUEST";
export const UPDATE_2FA_USER_RECOVERY_CODE_SUCCESS =
  "UPDATE_2FA_USER_RECOVERY_CODE_SUCCESS";

// Change password

// Privacy policies
