export type TBodyApiType = {
  userEmailAddress: string;
  userPassword: string;
  verifyToken: string;
  token: string;
  ipAddress: string;
  browserName: string;
  browserVersion: string;
  browserId: string;
  browserOS: string;
  browserEngine: string;
  macAddress: string;
  longitude: number;
  latitude: number;
  userId?: string;
  userPassKey?: string;
  userIs2FA?: boolean;
  userIs2FASetupCompleted?: boolean;
  userOTP?: string;
};
